-- ============================================
-- ARIA — Net New Tables
-- Domain context for predictive maintenance agents:
--   - shift / shift_assignment    (operator team awareness)
--   - logbook_entry               (operator notes for Sentinel/Investigator)
--   - equipment_kb                (Claude-curated equipment knowledge base)
--   - work_order                  (intervention tracking, generated by agent)
--   - failure_history             (past failures for pattern learning)
-- ============================================
-- ============================================
-- Shifts
-- ============================================
CREATE TABLE shift(
    id serial PRIMARY KEY,
    name varchar(50) NOT NULL UNIQUE,
    start_time time NOT NULL,
    end_time time NOT NULL,
    created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE shift_assignment(
    id serial PRIMARY KEY,
    shift_id integer NOT NULL REFERENCES shift(id) ON DELETE CASCADE,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    cell_id integer REFERENCES cell(id) ON DELETE CASCADE,
    assigned_date date NOT NULL,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_shift_assignment UNIQUE (shift_id, user_id, cell_id, assigned_date)
);

CREATE INDEX idx_shift_assignment_date ON shift_assignment(assigned_date);

CREATE INDEX idx_shift_assignment_cell ON shift_assignment(cell_id);

-- ============================================
-- Logbook (operator notes)
-- ============================================
CREATE TABLE logbook_entry(
    id serial PRIMARY KEY,
    cell_id integer NOT NULL REFERENCES cell(id) ON DELETE CASCADE,
    author_id integer REFERENCES users(id) ON DELETE SET NULL,
    entry_time timestamptz NOT NULL DEFAULT NOW(),
    category varchar(40) NOT NULL,
    severity varchar(20) NOT NULL DEFAULT 'info',
    content text NOT NULL,
    related_signal_def_id integer REFERENCES process_signal_definition(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_logbook_category CHECK (category IN ('observation', 'maintenance', 'incident', 'changeover', 'note')),
    CONSTRAINT chk_logbook_severity CHECK (severity IN ('info', 'warning', 'critical'))
);

CREATE INDEX idx_logbook_cell_time ON logbook_entry(cell_id, entry_time DESC);

CREATE INDEX idx_logbook_category ON logbook_entry(category);

-- ============================================
-- Equipment Knowledge Base
-- One curated entry per cell — built/refreshed by KB Builder agent.
-- ============================================
CREATE TABLE equipment_kb(
    id serial PRIMARY KEY,
    cell_id integer NOT NULL UNIQUE REFERENCES cell(id) ON DELETE CASCADE,
    equipment_type varchar(100),
    manufacturer varchar(100),
    model varchar(100),
    installation_date date,
    nominal_specs jsonb,
    common_failure_modes jsonb,
    maintenance_recommendations jsonb,
    notes text,
    last_updated_by varchar(50) DEFAULT 'kb_builder_agent',
    last_updated_at timestamptz NOT NULL DEFAULT NOW(),
    created_at timestamptz NOT NULL DEFAULT NOW()
);

-- ============================================
-- Work Orders (generated by Work Order Generator agent)
-- ============================================
CREATE TABLE work_order(
    id serial PRIMARY KEY,
    cell_id integer NOT NULL REFERENCES cell(id) ON DELETE CASCADE,
    title varchar(200) NOT NULL,
    description text,
    priority varchar(20) NOT NULL DEFAULT 'medium',
    status varchar(20) NOT NULL DEFAULT 'open',
    estimated_duration_min integer,
    required_parts jsonb,
    required_skills jsonb,
    suggested_window_start timestamptz,
    suggested_window_end timestamptz,
    created_by varchar(50) DEFAULT 'work_order_agent',
    assigned_to integer REFERENCES users(id) ON DELETE SET NULL,
    triggered_by_signal_def_id integer REFERENCES process_signal_definition(id) ON DELETE SET NULL,
    triggered_by_alert text,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    completed_at timestamptz,
    CONSTRAINT chk_wo_priority CHECK (priority IN ('low', 'medium', 'high', 'critical')),
    CONSTRAINT chk_wo_status CHECK (status IN ('open', 'in_progress', 'completed', 'cancelled'))
);

CREATE INDEX idx_work_order_cell ON work_order(cell_id);

CREATE INDEX idx_work_order_status ON work_order(status);

CREATE INDEX idx_work_order_priority ON work_order(priority);

-- ============================================
-- Failure History (for pattern learning)
-- ============================================
CREATE TABLE failure_history(
    id serial PRIMARY KEY,
    cell_id integer NOT NULL REFERENCES cell(id) ON DELETE CASCADE,
    failure_time timestamptz NOT NULL,
    resolved_time timestamptz,
    failure_mode varchar(100) NOT NULL,
    root_cause text,
    resolution text,
    parts_replaced jsonb,
    downtime_minutes integer,
    cost_estimate numeric(10, 2),
    work_order_id integer REFERENCES work_order(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_failure_history_cell_time ON failure_history(cell_id, failure_time DESC);

CREATE INDEX idx_failure_history_mode ON failure_history(failure_mode);

