/**
 * Print-only layout for a Work Order (M9.1).
 *
 * Wrapped in `.print-only` utility — hidden on screen, rendered under
 * `@media print`. Black on white, A4 portrait, sober hierarchy. QR code in
 * the footer encodes `{origin}/work-orders/{id}` so a tech can scan the
 * paper and pop the live detail on their phone.
 *
 * `qrcode` is dynamically imported so it stays out of the main bundle —
 * the module only downloads the first time an operator hits Print.
 */

import { useEffect, useState } from "react";
import type { WorkOrder } from "./types";

interface PrintableWorkOrderProps {
    wo: WorkOrder;
}

function formatLongDateTime(ts: string | null | undefined): string {
    if (!ts) return "—";
    const d = new Date(ts);
    if (Number.isNaN(d.getTime())) return "—";
    return d.toLocaleString("en-US", {
        weekday: "short",
        month: "short",
        day: "numeric",
        year: "numeric",
        hour: "2-digit",
        minute: "2-digit",
    });
}

function parseList(value: unknown): string[] {
    if (Array.isArray(value)) return value.map((v) => String(v)).filter(Boolean);
    if (typeof value === "string") {
        try {
            const parsed = JSON.parse(value);
            if (Array.isArray(parsed)) return parsed.map((v) => String(v)).filter(Boolean);
        } catch {
            // fallthrough
        }
        return value
            .split(",")
            .map((s) => s.trim())
            .filter(Boolean);
    }
    if (value && typeof value === "object") {
        const arr = value as Array<Record<string, unknown>>;
        return arr
            .map((it) =>
                Object.values(it)
                    .filter((v) => v !== undefined && v !== null)
                    .map((v) => String(v))
                    .join(" · "),
            )
            .filter(Boolean);
    }
    return [];
}

function useQrDataUrl(value: string): string | null {
    const [dataUrl, setDataUrl] = useState<string | null>(null);
    useEffect(() => {
        let cancelled = false;
        (async () => {
            try {
                const qrcode = await import("qrcode");
                const url = await qrcode.toDataURL(value, {
                    margin: 0,
                    width: 140,
                    errorCorrectionLevel: "M",
                });
                if (!cancelled) setDataUrl(url);
            } catch {
                if (!cancelled) setDataUrl(null);
            }
        })();
        return () => {
            cancelled = true;
        };
    }, [value]);
    return dataUrl;
}

export function PrintableWorkOrder({ wo }: PrintableWorkOrderProps) {
    const origin = typeof window !== "undefined" ? window.location.origin : "";
    const qrDataUrl = useQrDataUrl(`${origin}/work-orders/${wo.id}`);
    const actions = parseList(wo.recommended_actions);
    const parts = parseList(wo.required_parts);
    const skills = parseList(wo.required_skills);

    return (
        <article className="printable-work-order">
            <header className="pw-header">
                <div className="pw-header-left">
                    <h1 className="pw-title">{wo.title}</h1>
                    <p className="pw-subtitle">
                        Work order #{wo.id} · Priority {wo.priority} · Status{" "}
                        {wo.status.replace(/_/g, " ")}
                    </p>
                </div>
                <div className="pw-header-right">
                    <p className="pw-brand">ARIA</p>
                    <p className="pw-date">
                        Printed {formatLongDateTime(new Date().toISOString())}
                    </p>
                </div>
            </header>

            <section className="pw-meta">
                <PrintField label="Cell" value={wo.cell_name ?? `#${wo.cell_id}`} />
                <PrintField label="Created" value={formatLongDateTime(wo.created_at)} />
                {wo.trigger_anomaly_time && (
                    <PrintField
                        label="Anomaly time"
                        value={formatLongDateTime(wo.trigger_anomaly_time)}
                    />
                )}
                {wo.assigned_to_username && (
                    <PrintField label="Assigned to" value={wo.assigned_to_username} />
                )}
                {wo.estimated_duration_min != null && (
                    <PrintField
                        label="Estimated duration"
                        value={`${wo.estimated_duration_min} min`}
                    />
                )}
                {wo.generated_by_agent && <PrintField label="Source" value="Generated by agent" />}
            </section>

            {wo.description && (
                <PrintSection title="Description">
                    <p className="pw-paragraph">{wo.description}</p>
                </PrintSection>
            )}

            {wo.rca_summary && (
                <PrintSection title="Root cause analysis">
                    <p className="pw-paragraph">{wo.rca_summary}</p>
                </PrintSection>
            )}

            {actions.length > 0 && (
                <PrintSection title="Recommended actions">
                    <ol className="pw-ordered">
                        {actions.map((a) => (
                            <li key={a}>{a}</li>
                        ))}
                    </ol>
                </PrintSection>
            )}

            {parts.length > 0 && (
                <PrintSection title="Required parts">
                    <ul className="pw-bulleted">
                        {parts.map((p) => (
                            <li key={p}>{p}</li>
                        ))}
                    </ul>
                </PrintSection>
            )}

            {skills.length > 0 && (
                <PrintSection title="Required skills">
                    <ul className="pw-bulleted">
                        {skills.map((s) => (
                            <li key={s}>{s}</li>
                        ))}
                    </ul>
                </PrintSection>
            )}

            <PrintSection title="Technician sign-off">
                <div className="pw-signoff">
                    <SignoffField label="Started (date / time)" />
                    <SignoffField label="Completed (date / time)" />
                    <SignoffField label="Name" />
                    <SignoffField label="Signature" />
                </div>
            </PrintSection>

            <footer className="pw-footer">
                <div className="pw-footer-text">
                    <p className="pw-footer-title">Open in ARIA</p>
                    <p className="pw-footer-url">
                        {origin}/work-orders/{wo.id}
                    </p>
                </div>
                {qrDataUrl && (
                    <img src={qrDataUrl} alt={`QR code to work order ${wo.id}`} className="pw-qr" />
                )}
            </footer>
        </article>
    );
}

function PrintField({ label, value }: { label: string; value: string }) {
    return (
        <div className="pw-field">
            <span className="pw-field-label">{label}</span>
            <span className="pw-field-value">{value}</span>
        </div>
    );
}

function PrintSection({ title, children }: { title: string; children: React.ReactNode }) {
    return (
        <section className="pw-section">
            <h2 className="pw-section-title">{title}</h2>
            {children}
        </section>
    );
}

function SignoffField({ label }: { label: string }) {
    return (
        <div className="pw-signoff-field">
            <span className="pw-signoff-label">{label}</span>
            <span className="pw-signoff-line" aria-hidden />
        </div>
    );
}
