/**
 * Live-refresh hook for the Work Orders console (M9.1).
 *
 * Subscribes to `/api/v1/events` and invalidates the TanStack Query cache
 * on work-order lifecycle events so the list / detail auto-refresh without
 * a manual reload:
 *
 * - `work_order_ready` → a new WO was just generated by the agents. Invalidate
 *   the list to pull it in, plus the detail if we already have it cached.
 * - `rca_ready` → the Investigator finished analysing this WO. Optimistically
 *   flag the cached row with an RCA marker so the badge flips instantly,
 *   then invalidate list + detail to fetch the real `rca_summary` payload.
 *
 * Mirrors the `useAnomalyStream` pattern (M7.3): one socket per mount,
 * AbortController cleanup on unmount, status surfaced for debugging.
 */

import { useQueryClient } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import type { EventBusMap } from "../../lib/ws";
import { createWsClient } from "../../lib/ws";
import type { WorkOrder } from "./types";

const EVENTS_WS_URL = "/api/v1/events";

export type WorkOrdersStreamStatus = "connecting" | "open" | "closed" | "error";

export function useWorkOrdersStream(): { connectionStatus: WorkOrdersStreamStatus } {
    const [connectionStatus, setConnectionStatus] = useState<WorkOrdersStreamStatus>("connecting");
    const queryClient = useQueryClient();

    useEffect(() => {
        const controller = new AbortController();
        setConnectionStatus("connecting");

        const client = createWsClient<EventBusMap>({
            url: EVENTS_WS_URL,
            signal: controller.signal,
            onOpen: () => setConnectionStatus("open"),
            onClose: () => setConnectionStatus("closed"),
            onError: () => setConnectionStatus("error"),
            onEvent: (type, payload) => {
                if (type === "work_order_ready") {
                    const e = payload as EventBusMap["work_order_ready"];
                    queryClient.invalidateQueries({ queryKey: ["work-orders"] });
                    queryClient.invalidateQueries({
                        queryKey: ["work-order", e.work_order_id],
                    });
                    return;
                }
                if (type === "rca_ready") {
                    const e = payload as EventBusMap["rca_ready"];
                    // Optimistic flip on the list row(s) so the RCA badge
                    // appears instantly, before the re-fetch lands.
                    queryClient.setQueriesData<WorkOrder[]>(
                        { queryKey: ["work-orders"] },
                        (prev) => {
                            if (!prev) return prev;
                            return prev.map((wo) =>
                                wo.id === e.work_order_id
                                    ? { ...wo, rca_summary: wo.rca_summary ?? e.rca_summary }
                                    : wo,
                            );
                        },
                    );
                    queryClient.invalidateQueries({ queryKey: ["work-orders"] });
                    queryClient.invalidateQueries({
                        queryKey: ["work-order", e.work_order_id],
                    });
                }
            },
        });

        return () => {
            controller.abort();
            client.close(1000, "unmount");
        };
    }, [queryClient]);

    return { connectionStatus };
}
