export { default as AnomaliesPage } from "./AnomaliesPage";
export { default as ControlRoomPage } from "./ControlRoomPage";
export { default as DataPage } from "./DataPage";
export { default as DesignPage } from "./DesignPage";
export { default as LogbookPage } from "./LogbookPage";
export { default as LoginPage } from "./LoginPage";
export { default as OnboardingPage } from "./OnboardingPage";
export { default as ShiftsPage } from "./ShiftsPage";
export { default as WorkspacePage } from "./WorkspacePage";
